UI/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DTO;

namespace UI.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        UserBLL userbll = new UserBLL();
     
        public ActionResult Index()
        {
            UserDTO dto = new UserDTO();
            return View(dto);
        }

        [HttpPost]
        public ActionResult Index(UserDTO model)
        {
            if (ModelState.IsValid)
            {
                UserDTO user = userbll.GetUserWithUsernameAndPassword(model);
                if (user.ID != 0)
                {
                    UserStatic.UserID = user.ID;
                    UserStatic.isAdmin=user.isAdmin;
                    UserStatic.NameSurname = user.Name;
                    UserStatic.ImagePath = user.ImagePath;
                    LogBLL.AddLog(General.ProcessType.Login, General.TableName.Login, 12);
                    return RedirectToAction("Index", "Post");
                }
                else
                {
                    return View(model);
                }

            }
            else
                return View(model);
        }
    }
}

UI/Areas/Admin/Controllers/MetaController.cs
using BLL;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class MetaController : Controller
    {
        MetaBLL metabll = new MetaBLL();
        // GET: Admin/Meta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddMeta()
        {
            MetaDTO dto = new MetaDTO();
            return View(dto);
        }

        [HttpPost]
        public ActionResult AddMeta(MetaDTO model)
        {
            if (ModelState.IsValid)
            {
                if (metabll.AddMeta(model))
                {
                    ViewBag.ProcessState = General.Messages.AddSuccess;
                    ModelState.Clear();
                }
                else
                {
                    ViewBag.ProcessState = General.Messages.GeneralError;
                }
            }
            else
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }

            MetaDTO newmodel = new MetaDTO();
            return View(newmodel);
        }

        public ActionResult MetaList()
        {
            List<MetaDTO> model = new List<MetaDTO>();
            model = metabll.GetMetaData();
            return View(model);
        }

        public ActionResult UpdateMeta(int ID)
        {
            MetaDTO model= new MetaDTO();
            model = metabll.GetMetaWithID(ID);
            return View(model);
        }
        [HttpPost]
        public ActionResult UpdateMeta(MetaDTO model)
        {
            if(ModelState.IsValid)
            {
                if(metabll.UpdateMeta(model))
                {
                    ViewBag.ProcessState = General.Messages.UpdateSuccess;
                }
                else
                {
                    ViewBag.ProcessState=General.Messages.GeneralError;
                }
            }
            else
            {
                ViewBag.ProcessState= General.Messages.EmptyArea;
            }
            return View(model);
        }
    }
}

UI/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
    public class PostController : Controller
    {
        // GET: Admin/Post
        public ActionResult Index()
        {
            return View();
        }
    }
}

UI/Areas/Admin/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}
@model DTO.UserDTO
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Post | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Font Awesome -->
    <link href="~/Areas/Admin/Content/CSS/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link href="~/Areas/Admin/Content/CSS/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Areas/Admin/Content/CSS/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a><b>Admin Panel</b></a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form  method="post">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Username" name="Username">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Username)
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Password" name="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    @Html.ValidationMessageFor(x => x.Password)
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
            
            </form>

            <!-- /.social-auth-links -->


        </div>
        <!-- /.login-card-body -->
    </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Areas/Admin/Content/JS/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Content/JS/adminlte.min.js"></script>

</body>
</html>

UI/Areas/Admin/Views/Meta/AddMeta.cshtml
@{
    ViewBag.Title = "AddMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<section class="content-header">

    <h1>Add Meta Operation</h1>
    <ol class=" breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Add Meta</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary">Meta List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddMeta", "Meta", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/MetaForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Meta/MetaList.cshtml
@{
    ViewBag.Title = "MetaList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
@model List<DTO.MetaDTO>
<section class="content-header">

    <h1>Meta List</h1>
    <ol class=" breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Meta list</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Meta/AddMeta'">Add Meta</button>
</div>


<div class="card">
    <div class="card-header">
        <h3 class="card-title">Listeleme Ekranı</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th style="width: 20%">Name</th>
                    <th style="width: 60%">Meta Content</th>
                    <th style="width: 10%">Update</th>
                    <th style="width: 10%">Delete</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tbody>

                    <tr id="a_@item.MetaID">
                        <td>@item.Name</td>
                        <td>
                            @item.MetaContent
                        </td>
                        <td align="center" valign="middle">
                            <a href="/Admin/Meta/UpdateMeta/@item.MetaID">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/update.png" width="24px" />
                            </a>
                        </td>
                        <td align="center" valign="middle">
                            <a href="#">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/delete.png" width="24px" />
                            </a>
                        </td>

                    </tr>

                </tbody>

            }

            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Meta Content</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<script src="~/Areas/Admin/Content/JS/DeleteRecord.js"></script>

UI/Areas/Admin/Views/Meta/Partial/MetaForm.cshtml
@model DTO.MetaDTO
<div class="box-body">
    <div class="form-group">
        <label>Meta Content</label>
        @Html.TextBoxFor(x => x.MetaContent, new { @class = "form-control", @placeholder = "Meta Content" })
        @Html.ValidationMessageFor(x => x.MetaContent)
    </div>
    <div class="form-group">
        <label>Name</label>
        @Html.DropDownList("Name", new SelectList(new[] { "Keywords", "Description", "Author", "Twittercard" }), new { @class = "form-control select2" })
    </div>
    <input type="number" name="MetaID" value="@Model.MetaID" hidden />
    <div class="card-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</div>

UI/Areas/Admin/Views/Meta/UpdateMeta.cshtml
@{
    ViewBag.Title = "UpdateMeta";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">

    <h1>Update Meta Operation</h1>
    <ol class=" breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Meta</a></li>
        <li class="breadcrumb-item active"><a>Update Meta</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Meta/MetaList'">Meta List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("UpdateMeta", "Meta", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/MetaForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Post/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

UI/Areas/Admin/Views/Shared/MessageForm.cshtml
@using UI.Areas.Admin;

@if (ViewBag.ProcessState == BLL.General.Messages.AddSuccess)
{
    <div class="alert alert-success">
        <strong>Success!! Add Operation was completed Successfully</strong>

    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.EmptyArea)
{
    <div class="alert alert-danger">
        <strong>Error!! Please fill the neccessary area</strong>

    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.UpdateSuccess)
{
    <div class="alert alert-success">
        <strong>Success!! Update Operation was completed Successfully</strong>

    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.ImageMissing)
{
    <div class="alert alert-danger">
        <strong>Error!! Please select an image</strong>

    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.ExtensionError)
{
    <div class="alert alert-danger">
        <strong>Error!! Please select file with true extension</strong>

    </div>
}
else if (ViewBag.ProcessState == BLL.General.Messages.GeneralError)
{
    <div class="alert alert-danger">
        <strong>Error!! </strong>

    </div>
}